### PR TITLE
Issue328 winton bugs

### LINKED ISSUE #328: Winton errors with no ice
1. The Winton thermodynamics as implemented carries over the code that limits the ice if it drops below the minimum thickness threshold. This does not function correctly with the code in the `IceGrowth` class that updates the concentration.
2. The Winton thermodynamics try to solve the temperature balance even when there is zero ice. This goes poorly (NaN results).

### PR DESCRIPTION
**Pull request by timspainNERSC**
Add tests for the erroneous condition that arise with Winton thermodynamics and no ice and fix those tests.

Closes #328

### CODE REVIEW

**Review by draenog — COMMENTED** [review]
The commit replaces the existing test with  a new one. Could you explain why the old test is not kept (ideally it should go to a commit message).

**Review by draenog — COMMENTED** [review]
Why do you set cice to itts negative value instead of setting it to zero?  I am worried what happens if the function is called twice.

**Comment by timspainNERSC** [comment]
> The commit replaces the existing test with a new one. Could you explain why the old test is not kept (ideally it should go to a commit message).

Copy & paste became cut & paste, it seems.

**Comment by timspainNERSC** [comment]
> Why do you set cice to itts negative value instead of setting it to zero? I am worried what happens if the function is called twice.

If the function `lateralIceSpread()` is called twice then on the second call `cice[i]` will already be 0, so `cice[i] -= cice[i]` becomes 0 -= 0, which is still zero.

**Comment by draenog** [comment]
> > Why do you set cice to itts negative value instead of setting it to zero? I am worried what happens if the function is called twice.
> 
> If the function `lateralIceSpread()` is called twice then on the second call `cice[i]` will already be 0, so `cice[i] -= cice[i]` becomes 0 -= 0, which is still zero.

You are right. What confused me is the += operator. But maybe it is an indication that the code is not clear. What about changing this line to:
` cice[i] = (hice[i] > 0) ? cice[i] + deltaCIce[i] : 0.;`

**Comment by draenog** [comment]
I would myself probably clean git history in this repository by squashing 4a118f8, 33cc782 and b06111d. But I am also fine leaving as it is.

**Comment by timspainNERSC** [comment]
I'm currently in a [splitter](https://en.wikipedia.org/wiki/Lumpers_and_splitters) phase when it comes to git commits.

**Pull request merged**
