### PR TITLE
Create the namespaces, constants and conversion functions.

### PR DESCRIPTION
**Pull request by timspainNERSC**
A PR to ensure everyone agrees with how I laid out the new `constants.hpp` file.

### CODE REVIEW

**Comment by einola** [comment]
I approve. Very much in line with what I was thinking :)

**Comment by einola** [comment]
hold on ... you're not trying to merge this into ``develop``. Is this intentional?

**Comment by timspainNERSC** [comment]
> hold on ... you're not trying to merge this into `develop`. Is this intentional?

Yes. I was running through the process of making an issue branch from a feature branch, and merging it back in. This code is not needed for any of the code that's eventually going into development apart from what's in this Pull Request. If you want it in `develop` sooner, you can always make another Pull Request 🙂.

**Comment by einola** [comment]
Very good - just checking :)

**Pull request merged**
