### PR TITLE
Doxygen comments for all(?) of the headers

### PR DESCRIPTION
**Pull request by timspainNERSC**
What have I missed?

### CODE REVIEW

**Comment by auraoupa** [comment]
That looks pretty exhaustive, nice work ! If you want to have a look at the automatic documentation this will produce, just add the physics_sub branch at line 9 of .github/workflows/doxygen.yml so the documentation will be updated here : https://nextsimdg.github.io/nextsimdg/index.html

**Comment by timspainNERSC** [comment]
> That looks pretty exhaustive, nice work ! If you want to have a look at the automatic documentation this will produce, just add the physics_sub branch at line 9 of .github/workflows/doxygen.yml so the documentation will be updated here : https://nextsimdg.github.io/nextsimdg/index.html

Thanks, that was going to be my next question!

**Comment by timspainNERSC** [comment]
Something is not quite right.
Screenshot 2021-12-16 at 10 08 58

**Comment by auraoupa** [comment]
Yes the source directory name has changed from src to core so I updated the doxyfile

**Comment by auraoupa** [comment]
But it doesn't fix it, so I have to investigate a bit ...

**Comment by auraoupa** [comment]
I think it is okay now, the github page took a very long time to actualize...
Some errors still remain : the @detailed seem to no exist, maybe replace by @details ? (https://www.doxygen.nl/manual/commands.html#cmddetails)

**Comment by auraoupa** [comment]
Have a look at the class hierarchy  graph : https://nextsimdg.github.io/nextsimdg/inherits.html, don't know if it is informative but I find it kind of cool ;-)

**Comment by timspainNERSC** [comment]
> I think it is okay now, the github page took a very long time to actualize... Some errors still remain : the @Detailed seem to no exist, maybe replace by @details ? (https://www.doxygen.nl/manual/commands.html#cmddetails)

Well, I spelled that wrong in a lot of places🤦

**Comment by timspainNERSC** [comment]
> Have a look at the class hierarchy graph : https://nextsimdg.github.io/nextsimdg/inherits.html, don't know if it is informative but I find it kind of cool ;-)

That looks like it could be useful.

**Comment by timspainNERSC** [comment]
I realized the review that really matters is when everything gets merged with develop.

**Pull request merged**
